packages:
  - docs
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.13.2
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/tabler': ^1.2.18
  '@iconify/utils': ^2.3.0
  '@radix-ui/colors': ^3.0.0
  '@shikijs/vitepress-twoslash': ^3.4.2
  '@types/node': ^22.15.21
  '@unocss/core': ^66.1.2
  '@unocss/preset-attributify': ^66.1.2
  '@unocss/preset-mini': ^66.1.2
  '@unocss/preset-wind4': ^66.1.2
  '@unocss/rule-utils': ^66.1.2
  '@vueuse/core': ^13.3.0
  bumpp: ^10.1.1
  defu: ^6.1.4
  eslint: ^9.27.0
  eslint-plugin-format: ^1.0.1
  floating-vue: ^5.2.2
  lint-staged: ^16.0.0
  nimiq-css: ^1.0.0-beta.41
  nimiq-vitepress-theme: ^1.0.0-beta.41
  pathe: ^2.0.3
  pinia: ^3.0.2
  pnpm: ^10.11.0
  reka-ui: ^2.2.1
  simple-git-hooks: ^2.13.0
  tsx: ^4.19.4
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.2
  unocss-preset-animations: ^1.2.1
  unocss-preset-shadcn: ^0.5.0
  unplugin-vue-components: ^28.7.0
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.5
  vitepress-plugin-group-icons: ^1.5.5
  vitest: ^3.1.4
  vue: ^3.5.15
  vue-tsc: ^2.2.10
ignoredBuiltDependencies:
  - unrs-resolver
  - vue-demi
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - vue-demi
