packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.5.1
  '@antfu/ni': ^23.3.1
  '@antfu/utils': ^9.1.0
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/vitepress-twoslash': ^3.1.0
  '@types/node': ^22.13.9
  '@unocss/reset': ^66.0.0
  '@vueuse/core': ^12.8.2
  bumpp: ^10.0.3
  eslint: ^9.21.0
  floating-vue: ^5.2.2
  lint-staged: ^15.4.3
  pinia: ^3.0.1
  pnpm: ^10.5.2
  simple-git-hooks: ^2.11.1
  tsx: ^4.19.3
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unocss: ^66.1.0-beta.3
  '@unocss/core': ^66.1.0-beta.3
  unplugin-vue-components: ^28.4.1
  vite: ^6.2.0
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.3
  vitepress-plugin-group-icons: ^1.3.6
  vitest: ^3.0.7
  vue: ^3.5.13
