export const fluidSizeUtilities: [string, string[]][] = [
  ['text', ['font-size']],
  ['w', ['width']],
  ['h', ['height']],
  ['min-size', ['min-width', 'min-height']],
  ['max-size', ['max-width', 'max-height']],
  ['size', ['width', 'height']],
  ['min-w', ['min-width']],
  ['min-h', ['min-height']],
  ['max-w', ['max-width']],
  ['max-h', ['max-height']],
  ['my', ['margin-top', 'margin-bottom']],
  ['mx', ['margin-left', 'margin-right']],
  ['px', ['padding-left', 'padding-right']],
  ['py', ['padding-top', 'padding-bottom']],
  ['pt', ['padding-top']],
  ['pb', ['padding-bottom']],
  ['pl', ['padding-left']],
  ['pr', ['padding-right']],
  ['mt', ['margin-top']],
  ['mb', ['margin-bottom']],
  ['ml', ['margin-left']],
  ['mr', ['margin-right']],
  ['top', ['top']],
  ['bottom', ['bottom']],
  ['left', ['left']],
  ['right', ['right']],
  ['m', ['margin']],
  ['p', ['padding']],
  ['t', ['top']],
  ['b', ['bottom']],
  ['l', ['left']],
  ['r', ['right']],
  ['gap', ['gap']],
  ['gap-x', ['column-gap']],
  ['gap-y', ['row-gap']],
  ['rounded', ['border-radius']],
  ['leading', ['line-height']],
  ['tracking', ['letter-spacing']],
  ['shadow', ['box-shadow']],
  ['ring', ['--un-ring-width']],
  ['ring-offset', ['--un-ring-offset-width']],

  // You need to use `transform` to apply the `translate` utility
  ['translate', ['--un-translate-x', '--un-translate-y']],
  ['translate-x', ['--un-translate-x']],
  ['translate-y', ['--un-translate-y']],
  ['translate-z', ['--un-translate-z']],
]
